dist: focal
language: python
os: linux

install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports
  - sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
  - sudo add-apt-repository -y 'deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal main'
  - sudo apt-get update
  - sudo apt-get install -y golang-go python3-mysqldb
  - go get github.com/Clever/csvlint/cmd/csvlint
  - pip install -r requirements.txt

script:
  - ./check.sh
  - ./github-pages.sh

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: upload
  strategy: git
  committer_from_gh: true
  on:
    branch: master
