dist: focal
language: python
os: linux

install:
  - sudo add-apt-repository -y ppa:longsleep/golang-backports
  - sudo apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
  - sudo add-apt-repository -y 'deb [arch=amd64,arm64,ppc64el] http://ams2.mirrors.digitalocean.com/mariadb/repo/10.5/ubuntu focal main'
  - sudo apt-get update
  - sudo apt-get install -y golang-go python3-mysqldb figlet wkhtmltopdf wget
  - sudo apt-get remove -y wkhtmltopdf
  - wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
  - sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
  - rm wkhtmltox_0.12.6-1.focal_amd64.deb
  - export GOPATH=/tmp/go && go get github.com/Clever/csvlint/cmd/csvlint
  - pip install -r .exporter/requirements.txt

before_script:
  - ./.exporter/import_check.sh

script:
  - ./.exporter/exporter.sh
  - echo "auskunftsbegehren-adressen.cyber-perikarp.eu" > upload/CNAME
  - ./.exporter/export_check.sh

before_deploy:
  - cd $TRAVIS_BUILD_DIR

deploy:
  provider: pages
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: upload
  strategy: git
  edge: true
  skip_cleanup: true
  target_branch: gh-pages
  committer_from_gh: true
  on:
    branch: master
